import { Montserrat } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import Footer from "./user/components/Footer";
import ReduxProvider from "./api/providers/ReduxProvider";
import { GlobalProvider } from "./api/providers/GlobalContext";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable}`}>
        <ReduxProvider>
          <GlobalProvider>{children}</GlobalProvider>
        </ReduxProvider>
        <Footer />
      </body>
    </html>
  );
}
